name: ros2-ws-action
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]  
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1        

      - name: Checkout Dependencies
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/ichiro-its/kansei.git
          git clone https://github.com/ichiro-its/kansei_interfaces.git
          git clone https://github.com/ichiro-its/keisan.git
          git clone https://github.com/ichiro-its/aruku.git
          git clone https://github.com/ichiro-its/aruku_interfaces.git
          git clone https://github.com/ichiro-its/tachimawari.git
          git clone https://github.com/ichiro-its/tachimawari_interfaces.git
          git clone https://github.com/ichiro-its/suiryoku_interfaces.git
          git clone https://github.com/ichiro-its/atama_interfaces.git

      - name: Setup workspace
        uses: ichiro-its/ros2-ws-action/setup@v1.0.1

      - name: Build workspace
        uses: ichiro-its/ros2-ws-action/build@v1.0.1

      - name: Test workspace
        uses: ichiro-its/ros2-ws-action/test@v1.0.1
